In [1]:
import numpy as np 
import pandas as pd

In [9]:
df = pd.read_csv('data/visits.csv')
df.head()

,visit_id,patient_id,nurse_id,visit_start_time,visit_end_time,service_type,visit_location,nurse_notes
0,6a4a715f-94c5-4b5d-8f51-51f07f298fb6,P59581,N1565,2025-09-02 00:08:24,2025-09-02 00:55:24,Wound Care,East,The nurse changed the wound dressing. The pati...
1,27bfc4de-9dd2-4b6b-b05f-f9560a3fd00f,P66547,N5698,"August 24, 2025 10:42PM","August 25, 2025 12:12AM",General Check-up,East,The nurse reviewed the oxygen level. The patie...
2,9c2d0018-8f20-4789-a383-906d49042fbc,P47919,N3012,2025-09-02 11:07:33,2025/09/02 11:56,Physical Therapy,East,Review is required. The nurse assisted the mob...
3,bbedc08d-0ada-4c8f-bac4-3008ac279a01,P18359,N8991,2025-09-15 21:24:42,2025-09-15 22:12:42,General Check-up,North,Follow-up is required. The nurse reviewed the ...
4,155c3765-22d5-41cc-95f5-a94ef19748ae,P45602,N7948,2025-08-31 07:19:11,2025-08-31 07:47:11,Pyhcisal Therapy,North,ASAP is required. The nurse observed the patie...

In [10]:
df.dtypes

visit_id            object
patient_id          object
nurse_id            object
visit_start_time    object
visit_end_time      object
service_type        object
visit_location      object
nurse_notes         object
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   visit_id          1000 non-null   object
 1   patient_id        1000 non-null   object
 2   nurse_id          1000 non-null   object
 3   visit_start_time  1000 non-null   object
 4   visit_end_time    900 non-null    object
 5   service_type      1000 non-null   object
 6   visit_location    1000 non-null   object
 7   nurse_notes       900 non-null    object
dtypes: object(8)
memory usage: 62.6+ KB

In [12]:
df.isna().any()

visit_id            False
patient_id          False
nurse_id            False
visit_start_time    False
visit_end_time       True
service_type        False
visit_location      False
nurse_notes          True
dtype: bool

In [ ]:
## format the datetime columns
df['visit_start_time'] = pd.to_datetime(df['visit_start_time'], format='mixed')

In [18]:
df['visit_end_time'] = pd.to_datetime(df['visit_end_time'], format='mixed')

In [ ]:
## inspect any missing data in the visit_end_time column
df[df['visit_end_time'].isna()]

## it is possible that the visit_end_time is missing because onging vists but have to check the duration of the visit_start_time to confirm this

,visit_id,patient_id,nurse_id,visit_start_time,visit_end_time,service_type,visit_location,nurse_notes
11,c34e645d-6639-4c79-a281-a70e45368624,P98143,N9438,2025-08-25 14:00:00,NaT,General Check-up,Notrh,Review is required. ##--## The nurse monitored...
16,dce0428d-df95-4399-93cf-97122440fb10,P46024,N5472,2025-08-25 22:05:44,NaT,Physical Therapy,West,The nurse monitored the strength training. The...
22,d7cebb55-ad6d-49a5-a0ff-c513f6a9b456,P18780,N4701,2025-09-05 12:17:00,NaT,Medication Administration,North,The nurse provided the injection. The patient ...
24,e475f174-df8c-4b05-af82-ade9e5fd86e7,P79915,N4605,2025-08-21 01:15:00,NaT,Medication Administration,North,ASAP is required. The nurse provided the oral ...
27,81819e77-549d-4b5b-911a-cac30d9f913e,P65943,N8068,2025-09-03 02:21:45,NaT,Wound Care,East,The nurse changed the bandage. The patient is ...
...,...,...,...,...,...,...,...,...
957,cf26149b-3546-446f-8298-67e335a40629,P59451,N3997,2025-09-02 02:47:43,NaT,Physical Therapy,West,The nurse assisted the mobility exercise. The ...
971,8bb83f0e-4eae-4293-9c95-454d95a17b5d,P86804,N1960,2025-08-29 23:18:00,NaT,General Check-up,West,Review is required. The nurse checked the vita...
977,cc248126-04d2-4900-aea2-c4cb6a684ed3,P84794,N9821,2025-09-02 02:54:02,NaT,Wound Care,East,The nurse changed the incision site. The patie...
983,e523684e-7b18-4657-8358-2c5d10fc6129,P87348,N3681,2025-09-01 14:28:00,NaT,Wound Care,South,The nurse changed the wound dressing. The pati...
998,c7ae5d9a-8f3f-4c40-b211-85ca24a59bda,P34361,N3933,2025-08-25 03:57:29,NaT,Wound Care,South,Critical is required. The nurse applied the in...

In [ ]:
## inspect any missing data in the nurse_notes column
df[df['nurse_notes'].isna()]

,visit_id,patient_id,nurse_id,visit_start_time,visit_end_time,service_type,visit_location,nurse_notes
19,a04499ba-cea9-4fd1-91a5-4ef93a25980a,P67227,N7368,2025/08/31 19:55,2025-08-31 21:43:49,Wound Cae,North,NaN
85,a7c0d48c-26d5-47f4-a5c6-97b93fb08c0b,P60703,N1066,2025-08-20 20:30:41,2025-08-20 21:42:41,Medicatn Adminstratino,East,NaN
90,b5d08dee-8e18-4f56-bd6b-3801c163e84f,P12283,N9403,2025/09/16 04:27,2025-09-16 04:37:25,General Check-up,South,NaN
105,a94d75b9-64f2-4f90-86b3-f3bad0a0c2c3,P23151,N9438,2025-09-03 05:56:34,2025-09-03 06:46:34,Wound Care,East,NaN
111,57965f7b-ec1b-4439-8cac-b6eb7fa8d4ae,P13387,N3978,2025/09/18 00:21,"September 18, 2025 01:07AM",General Check-up,East,NaN
...,...,...,...,...,...,...,...,...
922,263e117a-9fbe-4399-8124-df594770e3a5,P47749,N2248,09/01/2025 09:57,2025-09-01 10:12:38,Wound Care,West,NaN
938,364104f6-cd23-44fe-80ef-5ef73b20bd26,P43492,N5633,2025-08-28 21:21:12,NaN,Wound Care,West,NaN
951,c1c93f32-b6fa-41e2-aa19-d00223d82e22,P64395,N8916,2025-09-09 13:53:08,NaN,Medication Administration,East,NaN
969,dc04178c-8238-43f8-8fd2-f95abff9dd91,P27118,N7325,2025-08-29 09:36:01,08/29/2025 11:16,Medication Administration,East,NaN
984,55bfac11-3826-43de-bcee-2eccfe4911eb,P94002,N8916,2025-08-24 10:59:24,2025-08-24 11:20:24,Physical Therapy,West,NaN