In [1]:
import numpy as np 
import pandas as pd

In [9]:
df = pd.read_csv('data/visits.csv')
df.head()

,visit_id,patient_id,nurse_id,visit_start_time,visit_end_time,service_type,visit_location,nurse_notes
0,6a4a715f-94c5-4b5d-8f51-51f07f298fb6,P59581,N1565,2025-09-02 00:08:24,2025-09-02 00:55:24,Wound Care,East,The nurse changed the wound dressing. The pati...
1,27bfc4de-9dd2-4b6b-b05f-f9560a3fd00f,P66547,N5698,"August 24, 2025 10:42PM","August 25, 2025 12:12AM",General Check-up,East,The nurse reviewed the oxygen level. The patie...
2,9c2d0018-8f20-4789-a383-906d49042fbc,P47919,N3012,2025-09-02 11:07:33,2025/09/02 11:56,Physical Therapy,East,Review is required. The nurse assisted the mob...
3,bbedc08d-0ada-4c8f-bac4-3008ac279a01,P18359,N8991,2025-09-15 21:24:42,2025-09-15 22:12:42,General Check-up,North,Follow-up is required. The nurse reviewed the ...
4,155c3765-22d5-41cc-95f5-a94ef19748ae,P45602,N7948,2025-08-31 07:19:11,2025-08-31 07:47:11,Pyhcisal Therapy,North,ASAP is required. The nurse observed the patie...

In [10]:
df.dtypes

visit_id            object
patient_id          object
nurse_id            object
visit_start_time    object
visit_end_time      object
service_type        object
visit_location      object
nurse_notes         object
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   visit_id          1000 non-null   object
 1   patient_id        1000 non-null   object
 2   nurse_id          1000 non-null   object
 3   visit_start_time  1000 non-null   object
 4   visit_end_time    900 non-null    object
 5   service_type      1000 non-null   object
 6   visit_location    1000 non-null   object
 7   nurse_notes       900 non-null    object
dtypes: object(8)
memory usage: 62.6+ KB

In [12]:
df.isna().any()

visit_id            False
patient_id          False
nurse_id            False
visit_start_time    False
visit_end_time       True
service_type        False
visit_location      False
nurse_notes          True
dtype: bool

In [ ]:
## format the datetime columns
df['visit_start_time'] = pd.to_datetime(df['visit_start_time'], format='mixed')

In [18]:
df['visit_end_time'] = pd.to_datetime(df['visit_end_time'], format='mixed')

In [ ]:
## inspect any missing data in the visit_end_time column
df[df['visit_end_time'].isna()]

## it is possible that the visit_end_time is missing because onging vists but have to check the duration of the visit_start_time to confirm this

,visit_id,patient_id,nurse_id,visit_start_time,visit_end_time,service_type,visit_location,nurse_notes
11,c34e645d-6639-4c79-a281-a70e45368624,P98143,N9438,2025-08-25 14:00:00,NaT,General Check-up,Notrh,Review is required. ##--## The nurse monitored...
16,dce0428d-df95-4399-93cf-97122440fb10,P46024,N5472,2025-08-25 22:05:44,NaT,Physical Therapy,West,The nurse monitored the strength training. The...
22,d7cebb55-ad6d-49a5-a0ff-c513f6a9b456,P18780,N4701,2025-09-05 12:17:00,NaT,Medication Administration,North,The nurse provided the injection. The patient ...
24,e475f174-df8c-4b05-af82-ade9e5fd86e7,P79915,N4605,2025-08-21 01:15:00,NaT,Medication Administration,North,ASAP is required. The nurse provided the oral ...
27,81819e77-549d-4b5b-911a-cac30d9f913e,P65943,N8068,2025-09-03 02:21:45,NaT,Wound Care,East,The nurse changed the bandage. The patient is ...
...,...,...,...,...,...,...,...,...
957,cf26149b-3546-446f-8298-67e335a40629,P59451,N3997,2025-09-02 02:47:43,NaT,Physical Therapy,West,The nurse assisted the mobility exercise. The ...
971,8bb83f0e-4eae-4293-9c95-454d95a17b5d,P86804,N1960,2025-08-29 23:18:00,NaT,General Check-up,West,Review is required. The nurse checked the vita...
977,cc248126-04d2-4900-aea2-c4cb6a684ed3,P84794,N9821,2025-09-02 02:54:02,NaT,Wound Care,East,The nurse changed the incision site. The patie...
983,e523684e-7b18-4657-8358-2c5d10fc6129,P87348,N3681,2025-09-01 14:28:00,NaT,Wound Care,South,The nurse changed the wound dressing. The pati...
998,c7ae5d9a-8f3f-4c40-b211-85ca24a59bda,P34361,N3933,2025-08-25 03:57:29,NaT,Wound Care,South,Critical is required. The nurse applied the in...

In [ ]:
## inspect any missing data in the nurse_notes column
df[df['nurse_notes'].isna()]

,visit_id,patient_id,nurse_id,visit_start_time,visit_end_time,service_type,visit_location,nurse_notes
19,a04499ba-cea9-4fd1-91a5-4ef93a25980a,P67227,N7368,2025/08/31 19:55,2025-08-31 21:43:49,Wound Cae,North,NaN
85,a7c0d48c-26d5-47f4-a5c6-97b93fb08c0b,P60703,N1066,2025-08-20 20:30:41,2025-08-20 21:42:41,Medicatn Adminstratino,East,NaN
90,b5d08dee-8e18-4f56-bd6b-3801c163e84f,P12283,N9403,2025/09/16 04:27,2025-09-16 04:37:25,General Check-up,South,NaN
105,a94d75b9-64f2-4f90-86b3-f3bad0a0c2c3,P23151,N9438,2025-09-03 05:56:34,2025-09-03 06:46:34,Wound Care,East,NaN
111,57965f7b-ec1b-4439-8cac-b6eb7fa8d4ae,P13387,N3978,2025/09/18 00:21,"September 18, 2025 01:07AM",General Check-up,East,NaN
...,...,...,...,...,...,...,...,...
922,263e117a-9fbe-4399-8124-df594770e3a5,P47749,N2248,09/01/2025 09:57,2025-09-01 10:12:38,Wound Care,West,NaN
938,364104f6-cd23-44fe-80ef-5ef73b20bd26,P43492,N5633,2025-08-28 21:21:12,NaN,Wound Care,West,NaN
951,c1c93f32-b6fa-41e2-aa19-d00223d82e22,P64395,N8916,2025-09-09 13:53:08,NaN,Medication Administration,East,NaN
969,dc04178c-8238-43f8-8fd2-f95abff9dd91,P27118,N7325,2025-08-29 09:36:01,08/29/2025 11:16,Medication Administration,East,NaN
984,55bfac11-3826-43de-bcee-2eccfe4911eb,P94002,N8916,2025-08-24 10:59:24,2025-08-24 11:20:24,Physical Therapy,West,NaN

In [20]:
df['visit_id'].nunique()

970

In [ ]:
# keep the last visit for each visit_id and drop the rest of the duplicates

df = df.sort_values('visit_start_time')
df = df.drop_duplicates(subset='visit_id', keep='last')
len(df)

970

In [25]:
# change the data type of the visit_id, patient_id and nurse_id columns to string
df['visit_id'] = df['visit_id'].astype('string')
df['patient_id'] = df['patient_id'].astype('string')
df['nurse_id'] = df['nurse_id'].astype('string')

In [26]:
# change the data type of service_type and visit_location
df['service_type'] = df['service_type'].astype('category')
df['visit_location'] = df['visit_location'].astype('category')

In [27]:
# change the data type of the nurse_notes column to string
df['nurse_notes'] = df['nurse_notes'].astype('string')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 970 entries, 835 to 122
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   visit_id          970 non-null    string
 1   patient_id        970 non-null    string
 2   nurse_id          970 non-null    string
 3   visit_start_time  970 non-null    datetime64[ns]
 4   visit_end_time    873 non-null    datetime64[ns]
 5   service_type      970 non-null    category
 6   visit_location    970 non-null    category
 7   nurse_notes       874 non-null    string
dtypes: category(2), datetime64[ns](2), string(4)
memory usage: 55.7 KB

In [ ]:
## check if there are any urgent notes in the nurse_notes column
df[df['nurse_notes'].str.contains(
    'urgent|asap|critical',
    case=False,
    na=False
)]

,visit_id,patient_id,nurse_id,visit_start_time,visit_end_time,service_type,visit_location,nurse_notes
121,e288d71b-4874-486a-826d-3b4e3598560f,P33297,N2536,2025-08-20 00:40:37,2025-08-20 01:01:37,Physical Therapy,Wsst,Critical is required. The nurse assisted the m...
313,4b3d0ec1-9a0b-4ae3-9f5a-3736f7c8dee4,P57919,N3507,2025-08-20 03:50:04,NaT,Wound Care,South,The nurse dressed the incision site. The patie...
785,e44dbd31-5a07-4908-8819-512d7d224666,P55858,N9821,2025-08-20 13:01:00,2025-08-20 13:17:00,Medication Administration,West,ASAP is required. The nurse delivered the oral...
24,e475f174-df8c-4b05-af82-ade9e5fd86e7,P79915,N4605,2025-08-21 01:15:00,NaT,Medication Administration,North,ASAP is required. The nurse provided the oral ...
781,826e8c7f-6f68-4435-99db-5e56093972a4,P30369,N8880,2025-08-21 22:08:06,2025-08-21 23:45:00,Wound Care,East,The nurse applied the incision site. The patie...
...,...,...,...,...,...,...,...,...
395,738ed0db-8dbb-4390-874b-ac8d2b218931,P60050,N5551,2025-09-17 05:10:14,2025-09-17 06:51:00,Wound Care,South,Urgent is required. The nurse changed the band...
941,9265e57e-c916-48a8-a2ad-14235bed3c8d,P83843,N9098,2025-09-17 05:54:00,2025-09-17 07:09:11,Wound Care,East,The nurse applied the wound dressing. The pati...
614,0473b24f-5df9-41a0-b056-e592b1f1959f,P84794,N4957,2025-09-17 08:55:38,2025-09-17 10:05:38,Physical Therapy,East,The nurse encouraged the strength training. Th...
973,c466951c-4ed8-4f41-bcf5-87fa2231de30,P57997,N8916,2025-09-17 11:39:22,2025-09-17 13:11:22,Physical Therapy,East,ASAP is required. The nurse encouraged the mob...
69,88683b99-84dd-47a4-aa5b-2ac1344c88c2,P25103,N1991,2025-09-17 23:57:12,2025-09-18 01:16:00,Medication Administration,North,The nurse delivered the oral dose. The patient...

In [ ]:
## create a new column called urgent_case that is True if the nurse_notes column contains the words urgent, asap or critical and False otherwise
df['urgent_case'] = df['nurse_notes'].str.contains(
        'urgent|asap|critical',
    case=False,
    na=False
)
df['urgent_case'].value_counts()

urgent_case
False    791
True     179
Name: count, dtype: Int64

In [37]:
## check if there any wording for revisit/follow up in the nurse_notes column
df[df['nurse_notes'].str.contains(
    'revisit|follow up|follow-up|followup',
    case=False,
    na=False
)]

,visit_id,patient_id,nurse_id,visit_start_time,visit_end_time,service_type,visit_location,nurse_notes,urgent_case
837,b16257ff-36be-4bee-91db-51f38c5533e6,P88018,N2340,2025-08-19 14:22:52,2025-08-19 15:02:00,Medication Administration,South,Follow-up is required. The nurse delivered the...,False
644,68f897eb-e031-43f7-99eb-f3a7db8898e1,P61936,N7969,2025-08-19 18:17:24,2025-08-19 19:16:00,Wound Care,South,Follow-up is required. The nurse applied the w...,False
832,8dd60537-4084-4161-a674-8be320f1a77f,P54147,N5170,2025-08-19 20:07:55,2025-08-19 21:40:55,Wound Care,East,The nurse dressed the wound dressing. The pati...,False
508,7fa24cd5-a00d-4df0-9279-3403b63661d3,P40492,N8286,2025-08-20 13:18:22,2025-08-20 14:29:22,Wound Care,North,The nurse changed the wound dressing. The pati...,False
959,0d587b1c-3023-4c92-976e-adef9cad430d,P95155,N4983,2025-08-20 14:45:31,2025-08-20 15:54:31,Medication Administration,West,The nurse administered the injection. The pati...,False
...,...,...,...,...,...,...,...,...,...
751,844a5a68-976c-430d-b70c-d106797d0e1c,P42892,N9880,2025-09-17 00:18:18,2025-09-17 02:11:18,Wound Care,South,Follow-up is required. The nurse applied the b...,False
89,afe0ffa5-0230-4dd6-9968-b47c2140fb8d,P82600,N8991,2025-09-17 09:19:04,2025-09-17 10:47:04,Physical Therapy,Notrh,The nurse monitored the gait practice. The pat...,False
206,4e42015d-68ad-440c-b3b9-165074836fcf,P37942,N2248,2025-09-17 10:55:00,2025-09-17 12:05:13,Wound Care,East,Follow-up is required. The nurse applied the b...,False
663,2923ebc2-4de9-46fa-86e5-3d1cabce1fa7,P29486,N3280,2025-09-17 18:36:55,2025-09-17 19:15:00,Medication Administration,West,The nurse delivered the injection. The patient...,False
426,f81cc162-0d4b-4687-9c4c-41b99a4f26ea,P56867,N3763,2025-09-17 18:46:24,2025-09-17 19:01:00,Medication Administration,West,Follow-up is required. The nurse administered ...,False

In [38]:
df['revisit_case'] = df['nurse_notes'].str.contains(
    'revisit|follow up|follow-up|followup',
    case=False,
    na=False
)
df['revisit_case'].value_counts()

revisit_case
False    877
True      93
Name: count, dtype: Int64

In [ ]:
# check the nurse note for the canceled visit or key wording for cancelation
df['nurse_notes'].str.contains(
    'cancel|cancellation|canceled|no show',
    case=False,
    na=False
).value_counts()
# so there is no note for cancellation in the nurse_notes column

nurse_notes
False    970
Name: count, dtype: Int64

In [41]:
df.dtypes

visit_id            string[python]
patient_id          string[python]
nurse_id            string[python]
visit_start_time    datetime64[ns]
visit_end_time      datetime64[ns]
service_type              category
visit_location            category
nurse_notes         string[python]
urgent_case                boolean
revisit_case               boolean
dtype: object